device:
  vendor: google_devices

platform:
  sepolicy_dirs:
    - hardware/google/pixel-sepolicy

includes:
  - ../../snippets/mainline_system.yml
  - ../../snippets/gms.yml
  - flipendo.yml

  # Irrelevant stock feature: silent factory OTAs
  - factoryota.yml

  # Apps that don't really need to be privileged
  - gcam.yml

  # Pixel-exclusive features that need additional support
  - dreamliner.yml
  - turbo.yml

filters:
  props:
    prefix:
      # Debug
      - log.tag.

    match:
      # P19: AOD settings without Soli
      - ro.vendor.aware_available

      # Debug
      - ro.llkd.enable
      - debug.sf.enable_egl_image_tracker

      # APEX
      - ro.apex.updatable

      # Misc
      - keyguard.no_require_sim
      - ro.com.android.prov_mobiledata
      - ro.control_privapp_permissions
      - ro.boot.vendor.overlay.theme
      - ro.surface_flinger.supports_background_blur

  presigned:
    match:
      # eSIM (P19 doesn't have this in sepolicy)
      - system_ext/priv-app/EuiccSupportPixel/EuiccSupportPixel.apk
      # Needs same signature as EuiccSupportPixel
      - product/priv-app/EuiccGoogle/EuiccGoogle.apk
      # TODO: is this really necessary?
      - system_ext/priv-app/EuiccSupportPixelPermissions/EuiccSupportPixelPermissions.apk

      # Apps updated by Play Store on stock
      # (most of these aren't bundled, but it doesn't hurt to keep a full list)
      - product/app/arcore/arcore.apk
      - product/app/CalculatorGooglePrebuilt/CalculatorGooglePrebuilt.apk
      - product/app/CalendarGooglePrebuilt/CalendarGooglePrebuilt.apk
      - product/app/Chrome-Stub/Chrome-Stub.apk
      - product/app/Chrome/Chrome.apk.gz
      - product/app/DevicePolicyPrebuilt/DevicePolicyPrebuilt.apk
      - product/app/Drive/Drive.apk
      - product/app/GoogleContacts/GoogleContacts.apk
      - product/app/GoogleTTS/GoogleTTS.apk
      - product/app/LatinIMEGooglePrebuilt/LatinIMEGooglePrebuilt.apk
      - product/app/Maps/Maps.apk
      - product/app/Photos/Photos.apk
      - product/app/PrebuiltDeskClockGoogle/PrebuiltDeskClockGoogle.apk
      - product/app/PrebuiltGmail/PrebuiltGmail.apk
      - product/app/SoundPickerPrebuilt/SoundPickerPrebuilt.apk
      - product/app/talkback/talkback.apk
      - product/app/Videos/Videos.apk
      - product/app/VoiceAccessPrebuilt/VoiceAccessPrebuilt.apk
      - product/app/WebViewGoogle-Stub/WebViewGoogle-Stub.apk
      - product/app/YouTube/YouTube.apk
      - product/app/YouTubeMusicPrebuilt/YouTubeMusicPrebuilt.apk
      - product/priv-app/AndroidAutoStubPrebuilt/AndroidAutoStubPrebuilt.apk
      - product/priv-app/CarrierServices/CarrierServices.apk
      - product/priv-app/DreamlinerPrebuilt/DreamlinerPrebuilt.apk
      - product/priv-app/EuiccGoogle/EuiccGoogle.apk
      - product/priv-app/FilesPrebuilt/FilesPrebuilt.apk
      - product/priv-app/GCS/GCS.apk
      - product/priv-app/GoogleCamera/GoogleCamera.apk
      - product/priv-app/GoogleDialer/GoogleDialer.apk
      - product/priv-app/HealthConnectPrebuilt/HealthConnectPrebuilt.apk
      - product/priv-app/HelpRtcPrebuilt/HelpRtcPrebuilt.apk
      - product/priv-app/MaestroPrebuilt/MaestroPrebuilt.apk
      - product/priv-app/OdadPrebuilt/OdadPrebuilt.apk
      - product/priv-app/Phonesky/Phonesky.apk
      - product/priv-app/PixelLiveWallpaperPrebuilt/PixelLiveWallpaperPrebuilt.apk
      - product/priv-app/PrebuiltBugle/PrebuiltBugle.apk
      - product/priv-app/PrebuiltGmsCore/PrebuiltGmsCoreSc.apk
      - product/priv-app/RecorderPrebuilt/RecorderPrebuilt.apk
      - product/priv-app/SafetyHubPrebuilt/SafetyHubPrebuilt.apk
      - product/priv-app/ScribePrebuilt/ScribePrebuilt.apk
      - product/priv-app/SecurityHubPrebuilt/SecurityHubPrebuilt.apk
      - product/priv-app/SettingsIntelligenceGooglePrebuilt/SettingsIntelligenceGooglePrebuilt.apk
      - product/priv-app/TurboPrebuilt/TurboPrebuilt.apk
      - product/priv-app/Velvet/Velvet.apk
      - product/priv-app/WellbeingPrebuilt/WellbeingPrebuilt.apk
      - system/app/CaptivePortalLoginGoogle/CaptivePortalLoginGoogle.apk
      - system/priv-app/DocumentsUIGoogle/DocumentsUIGoogle.apk
      - system/priv-app/NetworkStackGoogle/NetworkStackGoogle.apk

    prefix:
      - product/app/PixelCameraServices
      # Another app updated by Play Store on stock
      - product/priv-app/DevicePersonalizationPrebuiltPixel
      - product/priv-app/SCONE
      - product/priv-app/TipsPrebuilt

  sepolicy_dirs:
    match:
      # ramdump debugging
      - hardware/google/pixel-sepolicy/ramdump

  files:
    match:
      # P20
      - product/app/DevicePolicyPrebuilt/DevicePolicyPrebuilt.apk
      - product/app/DeviceStatisticsService/DeviceStatisticsService.apk
      - product/app/DiagnosticsToolPrebuilt/DiagnosticsToolPrebuilt.apk
      - product/app/MarkupGoogle/MarkupGoogle.apk
      - product/app/MicropaperPrebuilt/MicropaperPrebuilt.apk
      - product/app/NgaResources/NgaResources.apk
      - product/app/PixelThemesStub/PixelThemesStub.apk
      - product/app/PrebuiltGoogleAdservicesTvp/PrebuiltGoogleAdservicesTvp.apk
      - product/app/PrebuiltGoogleTelemetryTvp/PrebuiltGoogleTelemetryTvp.apk
      - product/app/SafetyRegulatoryInfo/SafetyRegulatoryInfo.apk
      - product/app/SoundAmplifierPrebuilt/SoundAmplifierPrebuilt.apk
      - product/app/SoundPickerPrebuilt/SoundPickerPrebuilt.apk
      - product/etc/permissions/com.google.android.hardwareinfo.xml
      - product/etc/sysconfig/nga.xml
      - product/framework/libhwinfo.jar
      - product/priv-app/AmbientSensePrebuilt/AmbientSensePrebuilt.apk
      - product/priv-app/BetterBug/BetterBug.apk
      - product/priv-app/CarrierMetrics/CarrierMetrics.apk
      - product/priv-app/HardwareInfo/HardwareInfo.apk
      - product/priv-app/HelpRtcPrebuilt/HelpRtcPrebuilt.apk
      - product/priv-app/MaestroPrebuilt/MaestroPrebuilt.apk
      - product/priv-app/OdadPrebuilt/OdadPrebuilt.apk
      - product/priv-app/OTAConfigNoZeroTouchPrebuilt/OTAConfigNoZeroTouchPrebuilt.apk
      - product/priv-app/PixelLiveWallpaperPrebuilt/PixelLiveWallpaperPrebuilt.apk
      - product/priv-app/SafetyHubPrebuilt/SafetyHubPrebuilt.apk
      - product/priv-app/SCONE/SCONE.apk
      - product/priv-app/ScribePrebuilt/ScribePrebuilt.apk
      - product/priv-app/SecurityHubPrebuilt/SecurityHubPrebuilt.apk
      - product/priv-app/SettingsIntelligenceGooglePrebuilt/SettingsIntelligenceGooglePrebuilt.apk
      - product/priv-app/Showcase/Showcase.apk
      - product/priv-app/TipsPrebuilt/TipsPrebuilt.apk
      - system_ext/app/EmergencyInfoGoogleNoUi/EmergencyInfoGoogleNoUi.apk
      - system_ext/priv-app/GoogleFeedback/GoogleFeedback.apk
      - system_ext/priv-app/NexusLauncherRelease/NexusLauncherRelease.apk
      - system_ext/priv-app/PixelSetupWizard/PixelSetupWizard.apk
      - system_ext/priv-app/QuickAccessWallet/QuickAccessWallet.apk
      - system_ext/priv-app/SettingsGoogle/SettingsGoogle.apk
      - system_ext/priv-app/StorageManagerGoogle/StorageManagerGoogle.apk
      - system_ext/priv-app/SystemUIGoogle/SystemUIGoogle.apk
      - system_ext/priv-app/UvExposureReporter/UvExposureReporter.apk
      - system_ext/priv-app/WallpaperPickerGoogleRelease/WallpaperPickerGoogleRelease.apk

      # P19: Soli
      - system_ext/priv-app/OsloFeedback/OsloFeedback.apk

      # P21
      - product/app/VoiceAccessPrebuilt/VoiceAccessPrebuilt.apk
      - product/etc/permissions/com.google.android.odad.xml

      # Diagnostics
      - product/priv-app/DiagnosticsToolPrebuilt/DiagnosticsToolPrebuilt.apk
      - product/etc/permissions/com.google.android.apps.diagnosticstool.xml

      # Accessibility gapps
      - vendor/etc/default-permissions/default-permissions_talkback.xml

      # Sysconfig
      - product/etc/sysconfig/allowlist_com.android.omadm.service.xml
      - product/etc/sysconfig/google.xml
      - product/etc/sysconfig/google_build.xml
      - product/etc/sysconfig/nexus.xml

      # Fonts
      - product/etc/fonts_customization.xml

      # Beta
      - system/app/BluetoothMigrationForBeta3User/BluetoothMigrationForBeta3User.apk
      - system_ext/priv-app/YadaYada/YadaYada.apk
      - product/priv-app/BetaFeedback/BetaFeedback.apk
      - product/priv-app/PixelSupportPrebuilt/PixelSupportPrebuilt.apk

      # Weather
      - product/priv-app/WeatherPixelPrebuilt/WeatherPixelPrebuilt.apk

      # Pixel Experience
      - product/etc/sysconfig/pixel_experience_2017.xml
      - product/etc/sysconfig/pixel_experience_2018.xml
      - product/etc/sysconfig/pixel_experience_2019.xml
      - product/etc/sysconfig/pixel_experience_2019_midyear.xml
      - product/etc/sysconfig/pixel_experience_2020.xml
      - product/etc/sysconfig/pixel_experience_2020_midyear.xml

      # Bluetooth
      - system/app/GoogleBluetoothLegacyMigration/GoogleBluetoothLegacyMigration.apk

      # Switch access
      - product/app/SwitchAccessPrebuilt/SwitchAccessPrebuilt.apk

      # AI Core (P21+)
      - product/priv-app/AICorePrebuilt/AICorePrebuilt.apk

      # Device diagnostics
      - system/priv-app/DeviceDiagnostics/DeviceDiagnostics.apk

      # Circle to search
      - product/priv-app/SearchSelectorPrebuilt/SearchSelectorPrebuilt.apk

      - product/priv-app/TetheringEntitlement/TetheringEntitlement.apk

      - system/bin/oem-iptables-init.sh

    prefix:
      # (Live) wallpapers
      - product/app/WallpapersBReel
      - product/app/PixelWallpapers
      - product/app/WallpaperEmojiPrebuilt

      # P20
      - product/etc/security/

      # P21
      - product/tts/google/
      - product/wallpaper/

      # P22
      - product/app/PixelThemesStub2022_and_newer/

      # Clocks
      - system_ext/priv-app/SystemUIClocks

      # SUW
      - system_ext/priv-app/SetupWizardPixelPrebuilt

      - product/priv-app/CarrierSettings
      - product/priv-app/DeviceIntelligenceNetworkPrebuilt
      - product/priv-app/GoogleRestorePrebuilt

      # Charger
      - vendor/etc/res/images/charger
      - vendor/etc/res/values/charger

  overlay_keys:
    match:
      # Safety
      - android:drawable/ic_safety_protection

      # SetupWizard annoyances
      - com.google.android.pixel.setupwizard/PixelSetupWizard:string/exit_to_action_in_initial_setup
      - com.google.android.pixel.setupwizard/PixelSetupWizard:string-array/deferred_medium_priority_actions

      # P19-20: use peak refresh rate when possible
      - android:string-array/config_highRefreshRateBlacklist

      # P19: Soli
      - com.android.settings:string/other_gestures_category_title
      - com.google.android.pixel.setupwizard:bool/show_air_gestures_opt_in

      # P19: face unlock debugging
      - android:string-array/config_restrictedImagesServices

      # Cast volume adjustment
      - android:bool/config_volumeAdjustmentForRemoteGroupSessions

      # Misc
      - android:bool/config_enableGeolocationTimeZoneDetection
      - android:bool/config_enablePrimaryLocationTimeZoneProvider
      - android:bool/config_enableSecondaryLocationTimeZoneProvider
      - android:string-array/config_accessibility_allowed_install_source
      - android:string-array/config_allowedSecureInstantAppSettings
      - android:string-array/config_disabledUntilUsedPreinstalledImes
      - com.android.providers.contacts:string/metadata_sync_pacakge
      - android:string/harmful_app_warning_title
      - com.google.android.permissioncontroller/PermissionControllerStyles:string/help_app_permissions
      - com.google.android.networkstack/NetworkStackConfig:bool/config_dhcp_client_hostname
      - android:string/config_secondaryLocationTimeZoneProviderPackageName
      - android:string/config_servicesExtensionPackage
      - android:bool/config_swipe_up_gesture_setting_available
      - android:bool/config_showGesturalNavigationHints
      - android:bool/config_volumeHushGestureEnabled
      - android:integer/config_defaultNightMode
      - android:string-array/config_batteryPackageTypeService
      - android:array/config_notificationMsgPkgsAllowedAsConvos
      - android:bool/config_bugReportHandlerEnabled
      - android:bool/config_defaultRingtonePickerEnabled
      - android:bool/config_profcollectReportUploaderEnabled
      - android:bool/config_sendPackageName
      - android:bool/config_smart_battery_available
      - android:bool/config_volumeShowRemoteSessions
      - android:dimen/config_highResTaskSnapshotScale
      - android:integer/config_storageManagerDaystoRetainDefault
      - android:string/android_start_title
      - android:string/android_upgrading_title
      - android:string/config_batterySaverScheduleProvider
      - android:string/config_emergency_dialer_package
      - android:string/config_incidentReportApproverPackage
      - android:string/config_powerSaveModeChangedListenerPackage
      - android:string/config_recentsComponentName
      - android:string/config_retailDemoPackage
      - android:string/config_retailDemoPackageSignature
      - android:string/config_secondaryHomePackage
      - com.android.settings:string-array/config_settings_slices_accessibility_components
      - com.android.settings:string/setup_fingerprint_enroll_finish_message
      - com.android.settings:string/suggested_fingerprint_lock_settings_summary
      - com.android.systemui:string-array/config_controlsPreferredPackages
      - com.android.systemui:bool/config_hspa_data_distinguishable
      - com.android.systemui:bool/config_touch_context_enabled
      - com.android.systemui:bool/config_wlc_support_enabled
      - com.android.systemui:drawable/ic_qs_branded_vpn
      - com.android.systemui:drawable/stat_sys_branded_vpn
      - com.android.systemui:string/config_dockComponent
      - com.android.systemui:string/config_screenshotEditor
      - com.android.phone:string-array/config_countries_to_enable_shortcut_view
      - com.android.phone:string/dialer_default_class
      - com.android.server.telecom:bool/config_hspa_data_distinguishable
      - com.android.server.telecom:string/call_diagnostic_service_package_name
      - com.android.server.telecom:string/dialer_default_class
      - com.android.traceur:bool/config_hspa_data_distinguishable
      - android:string-array/config_defaultFirstUserRestrictions
      - android:string-array/config_keep_warming_services
      - android:bool/config_enableFusedLocationOverlay
      - android:bool/config_enableGeocoderOverlay
      - android:bool/config_enableGeofenceOverlay
      - android:bool/config_enableNetworkLocationOverlay
      - android:string/config_deviceProvisioningPackage
      - android:string/default_wallpaper_component
      - android:bool/config_pinnerHomeApp
      - android:string/config_systemBluetoothStack
      - com.android.settings:string-array/slice_allowlist_package_names

      # Intentionally included: attention, speech recognition, search UI, smartspace, translation
      - android:string/config_defaultAccessibilityService
      - android:string/config_defaultAppPredictionService
      - android:string/config_defaultAssistantAccessComponent
      - android:string/config_defaultAutofillService
      - android:string/config_defaultDialer
      - android:string/config_defaultGallery
      - android:string/config_defaultListenerAccessPackages
      - android:string/config_defaultMusic
      - android:string/config_defaultSms
      - android:string/config_defaultAugmentedAutofillService
      - android:string/config_defaultBugReportHandlerApp
      - android:string/config_defaultContentCaptureService
      - android:string/config_defaultModuleMetadataProvider
      - android:string/config_defaultMusicRecognitionService
      - android:string/config_defaultProfcollectReportUploaderAction
      - android:string/config_defaultProfcollectReportUploaderApp
      - android:string/config_defaultTextClassifierPackage

    prefix:
      # Packages
      - com.android.managedprovisioning
      - com.android.providers.settings
      - com.android.simappdialog
      - com.google.android.cellbroadcastreceiver
      - com.google.android.cellbroadcastservice
      - com.google.android.documentsui

      # P19: Soli
      - com.android.settings:drawable/aware_
      - com.android.settings:drawable/$aware_
      - com.android.settings:string/aware_
      - com.android.settings:string/gesture_
      - com.android.settings:string/keywords_
      - com.android.settings:string/wake_screen_
      - com.android.settings:string/dialog_aware_
      - com.android.settings:string/ambient_display_wake_screen_

      # Settings tips
      - com.android.settings:string/tips_help_url_

      # Misc keys
      - android:bool/config_assist
      - android:drawable/ic_doc_
      - android:string-array/config_companionDevice
      - android:string/biometric_
      - android:string/config_system
      - android:string/widget_
      - com.android.settings:bool/config_
      - com.android.settings:string/display_white_balance_
      - com.android.settings:string/fingerprint_
      - com.android.settings:string/lock_settings_
      - com.android.settings:string/security_settings_
      - com.android.settings:string/security_settings_
      - com.android.settings:string/unlock_disable_frp_
      - com.android.systemui:string/branded_
      # Some ROMs remove these keys from the device tree
      - com.android.wifi.resources/WifiCustomization:integer/config_wifi_framework_wifi_score_

      # Fonts, feedback, help
      - android:string/config_bodyFont
      - android:string/config_feedbackIntent
      - android:string/config_headlineFont
      - android:string/config_helpIntent
      - android:string/config_helpPackage

      # Foldable state provider
      - android:string/config_deviceSpecificDeviceStatePolicyProvider

    substring:
      # P17-19: Active Edge
      - elmyra
      - avatar_image_descriptions
      - avatar_images
      - desc_ProfileIcons

    regex:
      # Not all custom ROMs have Google Sans
      - '^com\.google\.android\.pixel\.setupwizard/PixelSetupWizard:string/setup_.+_font_family$'
